spring:
  application:
    name: gateway
  boot:
    admin:
      client:
        url: http://localhost:8090

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ip: 127.0.0.1
    sentinel:
      transport:
        dashboard: localhost:8080

    gateway:
      routes:
        # 用户服务
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/api/user/**

        # 商品服务
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/api/product/**

        # 订单服务
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/api/order/**

        # 秒杀服务
        - id: service-seckill
          uri: lb://service-seckill
          predicates:
            - Path=/api/seckill/**

        # 支付服务
        - id: service-payment
          uri: lb://service-payment
          predicates:
            - Path=/api/payment/**

      # 全局跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

server:
  port: 8080
