spring:
  application:
    name: service-product
  boot:
    admin:
      client:
        url: http://localhost:8090

  datasource:
    url: jdbc:mysql://localhost:3306/db_product?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080

server:
  port: 8082

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

elasticsearch:
  host: localhost
  port: 9200
